In [ ]:
import torch

In [ ]:
Q = torch.tensor([[2., 1.]])
K = torch.tensor([[2., 1.],
                  [1., 2.]])
V = torch.tensor([[5., 5.],
                  [1., 9.]])

In [ ]:
scores = torch.matmul(Q, K.T)
weights = torch.softmax(scores, dim=1)
output = torch.matmul(weights, V)
print(scores)
print(weights)
print(output)

tensor([[5., 4.]])
tensor([[0.7311, 0.2689]])
tensor([[3.9242, 6.0758]])
